export const DOWN = 'DOWN'
export const LEFT = 'LEFT'
export const RIGHT = 'RIGHT'
export const UP = 'UP'
export const NEW_GAME = 'NEW_GAME'
export const GET_BOARD_WITH_INSERT = 'GET_BOARD_WITH_INSERT'
export const LOAD_SAVED_STATE = 'LOAD_SAVED_STATE'
export const SAVE = 'SAVE'
